import type { Milestone } from './types';

export const COUNTRY_DATA: Record<string, { male: number; female: number; average: number }> = {
  global: { male: 70.8, female: 75.6, average: 73.2 },
  iran: { male: 75.6, female: 78.4, average: 77.0 },
  japan: { male: 81.5, female: 86.9, average: 84.3 },
  switzerland: { male: 81.9, female: 85.6, average: 83.8 },
  usa: { male: 76.1, female: 81.1, average: 78.5 },
  germany: { male: 78.7, female: 83.3, average: 81.0 },
  sweden: { male: 81.3, female: 84.7, average: 83.0 },
  canada: { male: 79.7, female: 83.9, average: 81.7 },
  australia: { male: 81.2, female: 85.3, average: 83.2 },
  brazil: { male: 72.5, female: 79.4, average: 75.9 },
  india: { male: 69.5, female: 72.2, average: 70.8 },
  china: { male: 75.0, female: 80.8, average: 77.8 },
};

export const DEFAULT_MILESTONES: Milestone[] = [
  {
    id: 'first-word',
    age: 1,
    titleEn: 'First Word',
    titleFa: 'اولین کلمه',
    descriptionEn: 'Typically starts speaking first words around 12 months.',
    descriptionFa: 'شروع تکلم و گفتن اولین کلمات معمولاً در حدود یک سالگی.',
    icon: '💬',
    category: 'growth'
  },
  {
    id: 'school-start',
    age: 6,
    titleEn: 'Start of School',
    titleFa: 'شروع مدرسه',
    descriptionEn: 'The beginning of formal education and social expansion.',
    descriptionFa: 'آغاز آموزش رسمی و ورود به دنیای بزرگتر اجتماع.',
    icon: '🎒',
    category: 'growth'
  },
  {
    id: 'adolescence',
    age: 13,
    titleEn: 'Adolescence',
    titleFa: 'نوجوانی',
    descriptionEn: 'A period of rapid transformation, search for identity, and growth.',
    descriptionFa: 'دوران تحول سریع، جستجوی هویت و رشد بلوغ فکری.',
    icon: '⚡',
    category: 'growth'
  },
  {
    id: 'adulthood',
    age: 18,
    titleEn: 'Adulthood',
    titleFa: 'آغاز بزرگسالی',
    descriptionEn: 'Legal adulthood, voting rights, and choosing a career/study path.',
    descriptionFa: 'سن قانونی بزرگسالی، حق رای و انتخاب مسیر تحصیلی و شغلی.',
    icon: '🗝️',
    category: 'growth'
  },
  {
    id: 'college-graduation',
    age: 22,
    titleEn: 'Average Graduation',
    titleFa: 'فارغ‌التحصیلی دانشگاه',
    descriptionEn: 'Completing higher education and entering the professional world.',
    descriptionFa: 'پایان تحصیلات عالیه و ورود جدی به دنیای حرفه‌ای و کار.',
    icon: '🎓',
    category: 'career'
  },
  {
    id: 'saturn-return',
    age: 29,
    titleEn: 'Saturn Return',
    titleFa: 'بازگشت کیوان (Saturn Return)',
    descriptionEn: 'Astrological/philosophical milestone of maturity and major life decisions.',
    descriptionFa: 'نقطه تحول ستاره‌شناسی و فلسفی در اواخر دهه بیست زندگی.',
    icon: '🪐',
    category: 'growth'
  },
  {
    id: 'midlife-reflection',
    age: 40,
    titleEn: 'Midlife',
    titleFa: 'میانسالی',
    descriptionEn: 'A milestone for reflection, deeper self-awareness, and focus on legacy.',
    descriptionFa: 'زمان بازنگری در زندگی، خودآگاهی عمیق‌تر و تمرکز بر اثرگذاری.',
    icon: '🍂',
    category: 'growth'
  },
  {
    id: 'half-century',
    age: 50,
    titleEn: 'Half Century',
    titleFa: 'نیم قرن زندگی',
    descriptionEn: '50 years of living. A milestone of wisdom, resilience, and perspective.',
    descriptionFa: 'پنجاه سال زندگی. نقطه عطفی از خرد، تاب‌آوری و دیدگاه پخته.',
    icon: '🪙',
    category: 'general'
  },
  {
    id: 'retirement',
    age: 65,
    titleEn: 'Retirement Age',
    titleFa: 'سن بازنشستگی',
    descriptionEn: 'Transitioning from full-time career to pursuing personal hobbies and rest.',
    descriptionFa: 'انتقال از کار تمام‌وقت به سمت دنبال کردن علایق شخصی و استراحت.',
    icon: '🏖️',
    category: 'career'
  },
];

export const PHILOSOPHICAL_QUOTES = [
  {
    quoteEn: "We are not given a short life but we make it short, and we are not ill-supplied but wasteful of it.",
    quoteFa: "ما زندگی کوتاهی دریافت نمی‌کنیم بلکه آن را کوتاه می‌کنیم؛ و بی‌استعداد یا کم‌نعمت نیستیم بلکه در استفاده از آن زیاده‌روی می‌کنیم.",
    authorEn: "Seneca",
    authorFa: "سنکا"
  },
  {
    quoteEn: "You could leave life right now. Let that determine what you do and say and think.",
    quoteFa: "همین حالا هم می‌توانی زندگی را ترک کنی. بگذار این حقیقت، حاکم بر کارها، گفته‌ها و اندیشه‌هایت باشد.",
    authorEn: "Marcus Aurelius",
    authorFa: "مارکوس اورلیوس"
  },
  {
    quoteEn: "Assume you are dead. You have lived your life. Now, take what's left and live it properly.",
    quoteFa: "فرض کن که مرده‌ای و زندگی‌ات به پایان رسیده است. حالا آنچه باقی مانده را بردار و درست زندگی کن.",
    authorEn: "Marcus Aurelius",
    authorFa: "مارکوس اورلیوس"
  },
  {
    quoteEn: "Remembering that you are going to die is the best way I know to avoid the trap of thinking you have something to lose.",
    quoteFa: "به یاد داشتن اینکه روزی خواهی مرد، بهترین راهی است که می‌شناسم تا از تله این فکر که چیزی برای از دست دادن داری فرار کنی.",
    authorEn: "Steve Jobs",
    authorFa: "استیو جابز"
  },
  {
    quoteEn: "It is not death that a man should fear, but he should fear never beginning to live.",
    quoteFa: "انسان نباید از مرگ بترسد، بلکه باید از این بترسد که هرگز شروع به زندگی کردن نکند.",
    authorEn: "Marcus Aurelius",
    authorFa: "مارکوس اورلیوس"
  },
  {
    quoteEn: "Life is like a play: it's not the length, but the excellence of the acting that matters.",
    quoteFa: "زندگی مانند یک نمایشنامه است: طول آن مهم نیست، بلکه کیفیت بازیگری اهمیت دارد.",
    authorEn: "Seneca",
    authorFa: "سنکا"
  },
  {
    quoteEn: "How foolish to commit to plans when you cannot even be sure of tomorrow.",
    quoteFa: "چقدر نادان است کسی که خود را متعهد به برنامه‌های بلندمدت می‌کند در حالی که حتی از فردا مطمئن نیست.",
    authorEn: "Seneca",
    authorFa: "سنکا"
  },
  {
    quoteEn: "Khayyam, if you are drunk with wine, be happy / If you sit with a moon-faced beauty, be happy / Since the end of the world is non-existence / Assume you don't exist, and while you are, be happy.",
    quoteFa: "خیام اگر ز باده مستی خوش باش / با ماهرویی اگر نشستی خوش باش\nچون عاقبت کار جهان نیستی است / انگار که نیستی، چو هستی خوش باش",
    authorEn: "Omar Khayyam",
    authorFa: "خیام نیشابوری"
  },
  {
    quoteEn: "Yesterday is gone, tomorrow is not yet here. Only today is ours. Let us begin.",
    quoteFa: "دیروز گذشته است و فردا هنوز نیامده. فقط امروز مال ماست. پس آغاز کنیم.",
    authorEn: "Mother Teresa",
    authorFa: "مادر ترزا"
  },
  {
    quoteEn: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
    quoteFa: "برای داشتن یک زندگی شاد به چیزهای بسیار کمی نیاز است؛ همه‌چیز در درون خودت و در طرز تفکرت قرار دارد.",
    authorEn: "Marcus Aurelius",
    authorFa: "مارکوس اورلیوس"
  }
];

export const TRANSLATIONS = {
  en: {
    title: "Memento Mori",
    subtitle: "A philosophical visualizer of the days you are given.",
    getStarted: "Begin the Journey",
    enterBirthDetails: "Enter Your Birth Details",
    nameLabel: "Your Name / Label",
    birthDate: "Date of Birth",
    birthTime: "Time of Birth (Optional for seconds accuracy)",
    expectedLifespan: "Expected Lifespan (Years)",
    gender: "Gender",
    country: "Country / WHO Database",
    lifestyleFactors: "Lifestyle Factors (Adjusts Expectancy)",
    lifestyleIntro: "These choices reflect your daily habits and modify your virtual life expectancy based on actuarial statistics.",
    smoking: "Smoker (-10 years)",
    exercise: "Regular Exercise (+5 years)",
    diet: "Balanced Diet (+4 years)",
    stress: "High Stress Life/Job (-3 years)",
    sleep: "Regular Sleep (+3 years)",
    alcohol: "Heavy Alcohol Use (-5 years)",
    pollution: "High Pollution Exposure (-2 years)",
    genetics: "Good Genetics / Longevity (+4 years)",
    male: "Male",
    female: "Female",
    other: "Other / Prefer not to say",
    saveProfile: "Save and Enter Dashboard",
    editProfile: "Edit Profile",
    viewDashboard: "Dashboard",
    weeks: "Weeks",
    months: "Months",
    years: "Years",
    weeksView: "Weeks Grid",
    monthsView: "Months Grid",
    yearsView: "Years Grid",
    lifeLived: "Life Lived",
    lifeRemaining: "Life Remaining",
    timeLeft: "Time Remaining",
    timeLeftSub: "Years : Months : Days : Hours : Minutes : Seconds",
    quickStats: "Quick Statistics",
    lived: "Lived",
    remaining: "Remaining",
    totalExpected: "Total Expected",
    days: "Days",
    hours: "Hours",
    minutes: "Minutes",
    seconds: "Seconds",
    exactAge: "Precise Current Age",
    preciseAgeDesc: "{y} years, {m} months, {d} days, {h} hours, {mn} minutes, and {s} seconds",
    themes: "Themes",
    colorThemes: {
      zen: "Zen Garden (Nature)",
      cosmic: "Cosmic Dust (Midnight)",
      vintage: "Memento Mori (Crimson)",
      minimal: "Solitude (Minimal)",
      aura: "Ethereal Aura (Warm)",
    },
    languages: "Language / زبان",
    settings: "Settings",
    soundEffects: "Ticking Sound",
    ambientMusic: "Ambient Music",
    uncensoredMode: "Memento Mori (Realist Mode)",
    uncensoredDesc: "Displays statistics on mortality probability, and reflective prompts on death.",
    posthumousMode: "Hypothetical Death Mode",
    posthumousActive: "Hypothetical Death is active",
    posthumousText: "If today were your last day, what would remain unfinished? Meditate on this to prioritize your actions.",
    posthumousTitle: "Your Unfinished Legacy",
    obituaryTitle: "Reflective Obituary",
    obituaryText: "Here lies {name}, who lived {livedPercent}% of their projected path, leaving behind a blank canvas of future potential. They spent {daysLived} days on this earth. The remaining {daysLeft} days were returned to the cosmos.",
    mortalityProb: "Mortality Analytics",
    mortalityProb10Years: "Probability of mortality in the next 10 years",
    survivalProbability: "Survival curve (probability of reaching age X)",
    writeJournal: "Journal & Memories",
    journalInstructions: "Click or tap any square on the grid to write down a memory, milestone, or goal for that specific period.",
    journalTitle: "Memory / Milestone entry",
    titlePlaceholder: "Title (e.g. Moved to new city)",
    contentPlaceholder: "Write your thoughts, memory or goals here...",
    saveEntry: "Save Memory",
    deleteEntry: "Delete Memory",
    noEntries: "No memories recorded yet. Tap squares on the grid to create memories.",
    milestones: "Milestones",
    customMilestones: "Custom Goals / Milestones",
    addMilestone: "Add Milestone",
    milestoneAge: "Target Age",
    milestoneTitle: "Goal Title",
    milestoneDesc: "Goal Description",
    milestoneCat: {
      general: "General",
      milestone: "Key Milestone",
      growth: "Growth & Self",
      health: "Health",
      career: "Career / Education",
      relationship: "Relationship",
      travel: "Travel / Adventure"
    },
    exportPng: "Export Grid to Image",
    profiles: "Profiles",
    addProfile: "Add Profile",
    switchProfile: "Switch Profile",
    deleteProfile: "Delete Profile",
    deleteProfileConfirm: "Are you sure you want to delete this profile?",
    weeklyTip: "Hover or tap on any square to read milestones, view dates, and write journals.",
    backToSetup: "New User Setup",
    quotes: "Philosophical Meditations",
    nextQuote: "New Meditation",
    dayLabel: "Day",
    weekLabel: "Week",
    monthLabel: "Month",
    yearLabel: "Year",
    ageLabel: "Age",
    dateLabel: "Date",
    noteSaved: "Memory saved successfully.",
    noteDeleted: "Memory deleted.",
    soundSynthWarning: "Web Audio synth is enabled. Adjust volume if needed.",
    zoomIn: "Zoom In",
    zoomOut: "Zoom Out",
    resetZoom: "Reset Zoom",
    darkMode: "Dark Mode",
    birthYear: "Birth Year",
    birthMonth: "Birth Month",
    birthDay: "Birth Day",
    gregorianCalendar: "Gregorian",
    jalaliCalendar: "Jalali Calendar",
    soundOnHover: "Sound on Grid Hover",
    legacyTab: "Legacy Timeline",
    legacyIntro: "Meditate on the passage of time and events that will unfold in the world after your projected lifespan.",
    customLegacyEvents: "Post-Mortem Legacy Events",
    addLegacyEvent: "Add Legacy Event",
    legacyYearsPost: "Years after passing",
    webNotifications: "Philosophical Notifications",
    webNotificationsDesc: "Receive a reflective notification when a new week of your life begins.",
    notificationTitle: "Memento Mori",
    notificationBody: "A new week has begun. {livedPercent}% of your expected path is complete. Make this week count.",
    installApp: "Install App",
    countdownNote: "Timer Personal Note",
    countdownNoteDesc: "Show an editable personal note below the timer in fullscreen mode.",
  },
  fa: {
    title: "ممنتو موری (Memento Mori)",
    subtitle: "تصویرساز فلسفی روزهایی که به شما هدیه داده شده است.",
    getStarted: "آغاز سفر خویشتن",
    enterBirthDetails: "اطلاعات تولد خود را وارد کنید",
    nameLabel: "نام یا عنوان شما",
    birthDate: "تاریخ تولد",
    birthTime: "ساعت تولد (اختیاری برای محاسبه ثانیه)",
    expectedLifespan: "طول عمر مورد انتظار (سال)",
    gender: "جنسیت",
    country: "کشور / بانک اطلاعاتی WHO",
    lifestyleFactors: "سبک زندگی (تنظیم‌کننده امید به زندگی)",
    lifestyleIntro: "این گزینه‌ها بازتاب عادات روزانه شما هستند و بر اساس آمار بیمه، امید به زندگی فرضی شما را تغییر می‌دهند.",
    smoking: "مصرف سیگار (۱۰- سال)",
    exercise: "ورزش منظم (۵+ سال)",
    diet: "تغذیه سالم (۴+ سال)",
    stress: "زندگی پر استرس (۳- سال)",
    sleep: "خواب منظم و کافی (۳+ سال)",
    alcohol: "مصرف سنگین الکل (۵- سال)",
    pollution: "قرارگیری در معرض آلودگی هوا (۲- سال)",
    genetics: "ژنتیک و طول عمر خانوادگی (۴+ سال)",
    male: "مرد",
    female: "زن",
    other: "دیگر / ترجیح می‌دهم نگویم",
    saveProfile: "ذخیره و ورود به داشبورد",
    editProfile: "ویرایش مشخصات",
    viewDashboard: "داشبورد",
    weeks: "هفته‌ها",
    months: "ماه‌ها",
    years: "سال‌ها",
    weeksView: "شبکه هفته‌ها",
    monthsView: "شبکه ماه‌ها",
    yearsView: "شبکه سال‌ها",
    lifeLived: "زندگی سپری شده",
    lifeRemaining: "زندگی باقی‌مانده",
    timeLeft: "زمان باقی‌مانده",
    timeLeftSub: "سال : ماه : روز : ساعت : دقیقه : ثانیه",
    quickStats: "آمار سریع",
    lived: "سپری شده",
    remaining: "باقی‌مانده",
    totalExpected: "کل عمر مورد انتظار",
    days: "روز",
    hours: "ساعت",
    minutes: "دقیقه",
    seconds: "ثانیه",
    exactAge: "سن دقیق فعلی",
    preciseAgeDesc: "{y} سال و {m} ماه و {d} روز و {h} ساعت و {mn} دقیقه و {s} ثانیه",
    themes: "پوسته پیش‌فرض",
    colorThemes: {
      zen: "باغ ذن (طبیعت ملایم)",
      cosmic: "غبار کیهانی (نیمه‌شب آرام)",
      vintage: "یادآور مرگ (سرخ و کهن)",
      minimal: "تنهایی (مینیمال خاکستری)",
      aura: "هاله اثیری (گرم و خندان)",
    },
    languages: "Language / زبان",
    settings: "تنظیمات",
    soundEffects: "صدای تیک‌تاک",
    ambientMusic: "موسیقی پس‌زمینه آرام",
    uncensoredMode: "حالت ممانعت از فراموشی مرگ (واقع‌گرایانه)",
    uncensoredDesc: "نمایش آمارهای احتمال مرگ و پیام‌های تفکر برانگیز درباره مرگ.",
    posthumousMode: "حالت مرگ فرضی",
    posthumousActive: "حالت مرگ فرضی فعال است",
    posthumousText: "اگر امروز آخرین روز زندگی‌تان بود، چه کارهای نیمه‌کاره‌ای باقی می‌ماند؟ برای اولویت‌بندی کارهایتان روی این موضوع تامل کنید.",
    posthumousTitle: "میراث نیمه‌کاره شما",
    obituaryTitle: "آگهی ترحیم تامل‌برانگیز",
    obituaryText: "در اینجا {name} خفته است که {livedPercent}٪ از مسیر پیش‌بینی‌شده زندگی خود را سپری کرد و بوم سفیدی از پتانسیل‌های آینده را باقی گذاشت. او {daysLived} روز در این کره خاکی زیست. {daysLeft} روز باقی‌مانده به کیهان بازگردانده شد.",
    mortalityProb: "تحلیل احتمال مرگ",
    mortalityProb10Years: "احتمال فوت در ۱۰ سال آینده بر اساس سن شما",
    survivalProbability: "منحنی بقا (احتمال زنده ماندن تا سن X)",
    writeJournal: "دفترچه خاطرات و یادداشت‌ها",
    journalInstructions: "برای نوشتن خاطره، هدف یا نقطه عطف برای هر دوره، روی یکی از خانه‌های جدول کلیک کنید.",
    journalTitle: "ثبت خاطره / هدف",
    titlePlaceholder: "عنوان (مثلاً: نقل مکان به خانه جدید)",
    contentPlaceholder: "افکار، خاطره یا اهداف خود را اینجا بنویسید...",
    saveEntry: "ذخیره خاطره",
    deleteEntry: "حذف خاطره",
    noEntries: "هنوز هیچ خاطره‌ای ثبت نشده است. روی خانه‌های جدول کلیک کنید تا خاطره بنویسید.",
    milestones: "نقاط عطف",
    customMilestones: "اهداف و نقاط عطف شخصی",
    addMilestone: "افزودن هدف",
    milestoneAge: "سن هدف",
    milestoneTitle: "عنوان هدف",
    milestoneDesc: "توضیح هدف",
    milestoneCat: {
      general: "عمومی",
      milestone: "نقطه عطف اصلی",
      growth: "رشد شخصی",
      health: "سلامتی",
      career: "کار و تحصیل",
      relationship: "روابط",
      travel: "سفر و ماجراجویی"
    },
    exportPng: "خروجی گرفتن از شبکه به صورت تصویر",
    profiles: "پروفایل‌ها",
    addProfile: "افزودن پروفایل",
    switchProfile: "تغییر پروفایل",
    deleteProfile: "حذف پروفایل",
    deleteProfileConfirm: "آیا از حذف این پروفایل اطمینان دارید؟",
    weeklyTip: "نشانه گر را روی هر خانه نگه دارید یا روی آن ضربه بزنید تا تاریخ و نقاط عطف را ببینید یا خاطره بنویسید.",
    backToSetup: "تنظیمات کاربر جدید",
    quotes: "مراقبه‌های فلسفی",
    nextQuote: "مراقبه بعدی",
    dayLabel: "روز",
    weekLabel: "هفته",
    monthLabel: "ماه",
    yearLabel: "سال",
    ageLabel: "سن",
    dateLabel: "تاریخ",
    noteSaved: "یادداشت با موفقیت ذخیره شد.",
    noteDeleted: "یادداشت حذف شد.",
    soundSynthWarning: "سینت‌سایزر صوتی وب فعال است. در صورت نیاز ولوم را تنظیم کنید.",
    zoomIn: "بزرگ‌نمایی",
    zoomOut: "کوچک‌نمایی",
    resetZoom: "تنظیم مجدد",
    darkMode: "حالت شب (تاریک)",
    birthYear: "سال تولد",
    birthMonth: "ماه تولد",
    birthDay: "روز تولد",
    gregorianCalendar: "تقویم میلادی",
    jalaliCalendar: "تقویم شمسی",
    soundOnHover: "افکت صدای حرکت روی خانه‌ها",
    legacyTab: "سفر مابعد حیات",
    legacyIntro: "در جریان زمان و رویدادهایی که پس از عمر پیش‌بینی‌شده شما در جهان رخ خواهند داد، تأمل کنید.",
    customLegacyEvents: "رویدادهای شخصی پس از حیات",
    addLegacyEvent: "افزودن رویداد مابعد حیات",
    legacyYearsPost: "سال پس از فوت",
    webNotifications: "اعلان‌های تفکر برانگیز",
    webNotificationsDesc: "دریافت یک اعلان تامل‌برانگیز در آغاز هر هفته جدید از زندگی شما.",
    notificationTitle: "ممنتو موری (Memento Mori)",
    notificationBody: "یک هفته دیگر آغاز شد. {livedPercent}٪ از کل مسیر زندگی پیش‌بینی‌شده شما سپری شده است. قدر این هفته را بدانید.",
    installApp: "نصب برنامه",
    countdownNote: "یادداشت شخصی تایمر",
    countdownNoteDesc: "نمایش یک یادداشت قابل ویرایش در زیر تایمر در حالت تمام‌صفحه.",
  }
};
